name: Terraform Run

on:
  workflow_call:
    inputs:
      command:
        description: Terraform command to run after validate.
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform ${{ inputs.command }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - name: Checkov
        run: checkov -d .

      - name: Terraform Fmt Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_KEY || 'terraform.tfstate' }}" \
            -backend-config="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -backend-config="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -backend-config="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ inputs.command == 'plan' }}
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        if: ${{ inputs.command == 'apply' }}
        run: terraform apply -auto-approve -input=false -no-color