name: Terraform Apply (Main)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/**/*.yml"

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform-run.yml
    secrets: inherit
    with:
      command: apply
